stages:
  - deploy

deploy-to-ec2:
  stage: deploy
  tags:
    - test
  script:
    - echo "✅ CI/CD 트리거 정상 작동"
    - docker compose up -d --build
    - echo "현재 날짜:" $(date)
    - docker compose build | tee docker_build.log
