stages:
  - deploy

deploy-to-ec2:
  stage: deploy
  tags:
    - test
  script:
    - docker-compose down || true
    - docker-compose build | tee docker_build.log
    - docker-compose up -d --force-recreate
    - docker system prune -af --volumes
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
