version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx_test
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt:ro
     - ~/i13e102.p.ssafy.io.conf:/etc/nginx/conf.d/i13e102.p.ssafy.io.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    restart: always

  frontend-build:
    build:
      context: ./frontend/alpacar-vue
      dockerfile: Dockerfile
    image: frontend-build
    # 별도 컨테이너로 띄우지 않고 빌드 용도로만 사용
    entrypoint: ["true"]